version: '3.5'

services:
  rinha-de-backend-2023-api:
    container_name: rinha-de-backend-2023-api
    image: dotnet
    depends_on:
      - "postgres_database"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - rinha-de-backend-2023-network
      
  postgres_database:
      container_name: rinha-de-backend-2023-db
      image: postgres
      ports:
        - "5432:5432"
      volumes:
        - postgres:/data/postgres
      restart: always
      environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
        POSTGRES_DB: "rinha-de-backend-2023-db"
      networks:
        - rinha-de-backend-2023-network

networks:
  rinha-de-backend-2023-network:
    driver: bridge

volumes:
  postgres: