version: '3.5'

services:

    api0:
        container_name: rinha-de-backend-2023-api-0
        image: rinha-de-backend-2023-api
        depends_on:
          - db
        build:
          context: .
          dockerfile: Dockerfile
        environment:
          ASPNETCORE_ENVIRONMENT: "Production"
          ASPNETCORE_URLS: "http://localhost:8080"
        deploy:
          resources:
            limits:
              cpus: '0.3'
              memory: '350MB'
        network_mode: host

    api1:
      container_name: rinha-de-backend-2023-api-1
      image: rinha-de-backend-2023-api
      depends_on:
        - db
      build:
        context: .
        dockerfile: Dockerfile
      environment:
          ASPNETCORE_ENVIRONMENT: "Production"
          ASPNETCORE_URLS: "http://localhost:8081"
      deploy:
        resources:
          limits:
            cpus: '0.3'
            memory: '350MB'
      network_mode: host
    
    db:
        container_name: rinha-de-backend-2023-db
        image: postgres:16.1
        ports:
        - "5432:5432"
        volumes:
        - postgres:/data/postgres
        restart: always
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
            POSTGRES_DB: "rinha-de-backend-2023-db"
        deploy:
          resources:
            limits:
              cpus: '0.8'
              memory: '2.5GB'
        network_mode: host

    load-balancer:
      container_name: rinha-de-backend-2023-load-balancer
      image: nginx:1.25.3
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - api0
        - api1
      ports:
        - "9999:9999"
      deploy:
        resources:
          limits:
            cpus: '0.1'
            memory: '100MB'
      network_mode: host

volumes:
  postgres:
