version: '3.5'

services:

    api1:
        container_name: rinha-de-backend-2023-api-1
        image: rinha-de-backend-2023-api
        depends_on:
          - db
        build:
          context: .
          dockerfile: Dockerfile
        expose:
        - "80"
        deploy:
          resources:
            limits:
              cpus: '0.25'
              memory: '0.5GB'

    api2:
      container_name: rinha-de-backend-2023-api-2
      image: rinha-de-backend-2023-api
      depends_on:
        - db
      build:
        context: .
        dockerfile: Dockerfile
      expose:
        - "80"
      deploy:
        resources:
          limits:
            cpus: '0.25'
            memory: '0.5GB'
    
    db:
        container_name: rinha-de-backend-2023-db
        image: postgres:16.1
        ports:
        - "5432:5432"
        volumes:
        - postgres:/data/postgres
        restart: always
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
            POSTGRES_DB: "rinha-de-backend-2023-db"
        deploy:
          resources:
            limits:
              cpus: '0.75'
              memory: '1.5GB'

    nginx:
      container_name: rinha-de-backend-2023-load-balancer
      image: nginx:1.25.3
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - api1
        - api2
      ports:
        - "9999:9999"
      deploy:
        resources:
          limits:
            cpus: '0.25'
            memory: '0.5GB'

volumes:
  postgres:
